### ISSUE TITLE
Избежать Дублирование номеров доверенностей при копировании 

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#10]
При копировании заказов, по которым уже были выписаны доверенности, доверенности создаются с одним и тем же номером!

**Comment by AnnaSalikova** [comment]
Не удалось воспроизвести ситуацию с дублированием номеров - документу доверенность присваивается следующий номер по порядку. Опишите пожалуйста последовательность действий, которые привели к формированию доверенностей с одинаковыми номерами.

**Comment by OTimoshkin** [comment]
ок, как повторится, опишу подробнее

**Comment by AnnaSalikova** [comment]
Дублирование не воспроизводится. При смене организации не перезаписывался номер документа. Исправелно
