### ISSUE TITLE
Самопроизвольное удаление информации о заявке перевозчику

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#11]
![image](https://user-images.githubusercontent.com/27953665/78389131-e3087200-75ea-11ea-8c39-80e5eeecd429.png)
![image](https://user-images.githubusercontent.com/27953665/78389167-f4ea1500-75ea-11ea-88af-4b5d0b276c21.png)
![image](https://user-images.githubusercontent.com/27953665/78389202-04695e00-75eb-11ea-896e-e2b023622f9e.png)

В каких-то случаях происходит обнуление суммы заявки. Я не могу отследить в каких. Но точно так происходит. В данном заказе оператор отправила заявку и в ней была указана сумма указана 0. 
Также удалились следы отправленной заявки. Но в системной учетной записи почты, вероятно, которую вы создали, думаю, вы найдете в отправленных заявку по данному водителю.
Коротко о проблеме:
- удаляются суммы заявки за перевозку, удаляется заказ перевозчику из истории документов
при этом форма в части остальной информации остается заполненной.

**Comment by AnnaSalikova** [comment]
Добрый день, Воспроизвести не удалось. В базе отсутствует помеченный на удаление Заказ поставщику на перевозку, при этом действительно есть письмо от  2 апреля с суммой заявки 25000. Документ может отсутствовать только если не был создан, либо если был создан и удален из базы. Это может происходить из-за сбоя связи с сервером.  Если сумму заявки указать в форме Управление доставкой, она выводится в печатную форму заявки, но если при этом не нажать кнопку Сохранить в форме Управление доставкой,  сумма не будет сохранена. Возможно имело место что-то подобное. Дополнительно для поиска возможных причин будет проведен анализ журнала регистрации, проверена возможность включить верисионирование для Заказа покупателя. Версионирование позволяет отслеживать изменение реквизитов и сохранять историю их изменения. Правда это может привести к замедлению работы базы. О результатах расследования сообщу, когда они появятся

**Comment by OTimoshkin** [comment]
опять тоже самое произошло
![image](https://user-images.githubusercontent.com/27953665/78809832-2a6a7600-79d0-11ea-98b4-da1fba2dc126.png)

**Comment by OTimoshkin** [comment]
возможно, что это происходит, когда другой пользователь просматривает заказ, либо еще как-то работает. Но, сброса данных заявок другой пользователь точно не осуществлял.

**Comment by OTimoshkin** [comment]
![image](https://user-images.githubusercontent.com/27953665/78879622-cfcb2b80-7a5c-11ea-90a9-1ce5e6fbca44.png)
![2020-04-09 12-21-18 Скриншот экрана](https://user-images.githubusercontent.com/27953665/78879669-e1143800-7a5c-11ea-9510-11fb1becdc6b.jpg)

**Comment by OTimoshkin** [comment]
еще один пример
