### ISSUE TITLE
При копировании заказа меняется поставщик

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#12]
![image](https://user-images.githubusercontent.com/27953665/78395109-8eb6bf80-75f5-11ea-8be9-57e8d631fbf5.png)
![image](https://user-images.githubusercontent.com/27953665/78395143-9fffcc00-75f5-11ea-8a8a-1cb5809a066a.png)

При копировании заказа меняется поставщик. Не считаю это правильным.

**Comment by AnnaSalikova** [comment]
Добрый день.  При создании заказа покупателя (в том числе копированием) подставляется последний поставщик из истории. Вас не устраивает этот функционал, исправить, чтобы не заполнялся по истории?

**Comment by OTimoshkin** [comment]
Да, меня не устраивает функционал, когда при копировании идентичного заказа подставляется последний использованный поставщик из другого, совершенного не связанного с этим заказом заказа.
Например: Я отгрузил газоблок от Борского силикатного завода, для Гриша Саров. Далее я решил скопировать заказ Андрея Торбеево, который ранее грузился от ТПК Строймаркет, в результате я вижу, что подставляется поставщик "Борский силикат".
Мне нужно, чтобы при копировании заказа заказ копировался и подставлялся поставщик "ТПК СТРОЙМАРКЕТ"

**Comment by OTimoshkin** [comment]
Также нужно, чтобы при копировании сохранялись данные введенные ранее в форму

**Comment by AnnaSalikova** [comment]
Механизм копирования формы не разрабатывался в рамках ТЗ. Только функционал подставления данных из истории (телефоны, адреса электронной почты).
Подстановку поставщика при копировании исправляем: будет подставляться поставщик не по истории, а из скопированного документа. В новом заказе покупателя поставщик будет пустой.
Для доработки механизма копирования Управления доставкой  от вас нужно 
1. Список полей, которые должны копироваться в Управлении доставкой при копировании заказа покупателя. 
2. Для полей, которые заполняются по истории напишите пожалуйста как делать заполнение при копировании - по истории или значениями из исходного заказа покупателя. 
Пришлите пожалуйста на почту список этих полей.

**Comment by OTimoshkin** [comment]
Список полей, которые должны копироваться:
![image](https://user-images.githubusercontent.com/27953665/78976360-b094d280-7b1e-11ea-8ba3-27c4a67343b4.png)
Это список полей для копирования 1: поле цены поставщика не скопировалось! Нужно, чтобы копировалось.

![image](https://user-images.githubusercontent.com/27953665/78976755-81cb2c00-7b1f-11ea-8503-aafa751924ea.png)
![image](https://user-images.githubusercontent.com/27953665/78976804-9c9da080-7b1f-11ea-84f8-0676b1ecc95a.png)

это список для копирования 2

Причем копируются только данные формы, документы не копируются, не создаются и не проводятся (платежки, доверенности, приходные, счета и проч.)

**Comment by AnnaSalikova** [comment]
Исправлено
