### ISSUE TITLE
При создании нового пользователя и выдачи разрешения не даются права

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#13]
Если создан новый пользователь, выходит сообщение, о том, что у нового пользователя нет прав на запуск УНФ

**Comment by AnnaSalikova** [comment]
Добрый день. Проверьте, что вы до конца выполнили настройку доступа для нового пользователя. 
Как создавать нового пользователя описано здесь: https://1cfresh.com/articles/user_new
Как давать пользователю права на запуск приложений описано здесь: https://1cfresh.com/articles/user_apprights
Права доступа новому пользователю в УНФ можно назначить в разделе Компания - Администрирование- настройки пользователей и прав - Пользователи - в карточке пользователя по гиперссылке "Права доступа".
![image](https://user-images.githubusercontent.com/63094191/78751699-ead66680-799c-11ea-802b-f14f35baf043.png)
