### ISSUE TITLE
При копировании заказа, приходится нажимать "перезаполнить", чтобы сделать доверенность.

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#14]
1) Сделали доверенность, заявку перевозчику, приход и прочее
2) Скопировали заказ
3) в скопированном заказе, при печати доверенности через форму Управление ДОставкой, доверенность печатается от ИП Тимошкина О.В.
4) Чтобы исключить данную ошибку, приходится переходить во вкладку документы и нажимать "перезаполнить"

Считаю, что все должно работать без действия 4. Просьба продумать механизм копирования заказов и протестировать поведение более детально.
![2020-04-07 18-28-59 Скриншот экрана](https://user-images.githubusercontent.com/27953665/78689802-671a6c80-78ff-11ea-9b3d-4f9b15bd9cf3.jpg)

![2020-04-07 18-30-12 Скриншот экрана](https://user-images.githubusercontent.com/27953665/78689791-641f7c00-78ff-11ea-91b9-90ff1c171de7.jpg)
![2020-04-07 18-28-38 Скриншот экрана](https://user-images.githubusercontent.com/27953665/78689795-65e93f80-78ff-11ea-8936-e08cc6b5f0ec.jpg)

**Comment by AnnaSalikova** [comment]
Добрый день.  проверила проблему на тестовой базе
Проверила на рабочей базе (см документы к заказу покупателя от 08.04.2019. помеченные на удаление): 
1. В печатную форму доверенности подставляется та организация, которая указана в поле Организация в группе Поставщик. 
2. Если после заполнения доверенности вы поменяете организацию, то доверенность придется перезаполнять. До этого доверенность можно только создать (по кнопке Создать или отправить Доверенность)
3. Обнаружила у вас в базе ошибки при заполнении документов. Подробный разбор отправила письмом.
4. Если у вас проблема сохраняется, предлагаю созвониться в скайп и через демонстрацию экрана вы покажите последовательность ваших действий, приводящих к ошибке, чтобы нам удалось ее воспроизвести.
