### ISSUE TITLE
Пропадают цены поставщика

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#17]
скинул видео в скайп:
1) зашел в заказ
2) попечатал в форме управления доставки - конкретно, изменил сумму заявки
3) вышел - цены поставщика закупочные пропали из табличной части

**Comment by AnnaSalikova** [comment]
ошибку взяли в работу. Ранее ее уже исправляли, почему возникла снова выясним и исправим. Цены в заказе появятся, если закрыть заказ покупателя и открыть его снова
