### ISSUE TITLE
ошибка при завершении заказа

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#18]
![image](https://user-images.githubusercontent.com/27953665/78974314-64e02a00-7b1a-11ea-9673-ef21f442c964.png)

**Comment by AnnaSalikova** [comment]
Это не ошибка, сообщение относится к типовому функционалу УНФ.   Консультация по типовому функционалу может быть дана после утверждения формат работы.  так же для изучения типового функционала вы можете самостоятельно ознакомиться с руководством по УНФ от фирмы 1с на сайте ИТС и со справкой.
