### ISSUE TITLE
ошибка: подставляется почта, которая не имеет отношения к поставщику

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#19]
Подставляется почта в форме УпД (управление доставкой), которая не имеет отношения к поставщику. Ранее с данным поставщиком данная почта вряд ли употреблялась. Почта, если и должна подставляться, то только та, которая имеет отношение к этому поставщику (если ему ранее посылали на нее или забита была в карточке контрагента поставщика)

![image](https://user-images.githubusercontent.com/27953665/78977117-3bc29800-7b20-11ea-8284-3f71ca7f36f5.png)

**Comment by AnnaSalikova** [comment]
Добрый день, Олег, воспроизвести не удалось. нужны уточнения: 
1. Каким образом вы создали заказ покупателя?
2. вы меняли поставщика, грузоотправителя в форме, организацию? в какой последовательности?
3. При открытии формы сразу эта почта была подставлена?
