### ISSUE TITLE
Ошибка: Доверенность не выходит на печать, или выходит через раз

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#21]
Ошибка: Доверенность не выходит на печать, или выходит через раз, при этом, кнопка "отправить доверенность работает более менее надежно"

**Comment by OTimoshkin** [comment]
видео в скайпе

**Comment by AnnaSalikova** [comment]
Печатная форма доверенности формируется только из документа Доверенность. Если документ Доверенность не создан, то печатная форма не формируется. Доверенность создается либо по кнопке Отправить доверенность. либо по кнопке Создать на закладке Документы напротив Доверенность. 
Анализ базы показал: документ Доверенность № 20 сформирован 10.04.2020 11:55:14. На видео видно, что попытка печати доверенности выполнялась в 11:54, то есть до того, как был сформирован документ Доверенность. 
Указанное поведение программы не является ошибкой.

**Comment by OTimoshkin** [comment]
Анна, я настаиваю на том, чтобы при нажатии кнопки "Печать доверенности" выходила доверенность. Делать нужно для идиотов, т.е. для нас.

**Comment by OTimoshkin** [comment]
И сразу нужно затачиваться на то, что мы идиоты. И мы не будем руководствоваться вашей "правильной логикой", она для нас слишком извращенно сложная.

**Comment by OTimoshkin** [comment]
Печать доверенности означает для нас печать доверенности. А не внутренние процессы внутри микросхем ноутубука.

**Comment by OTimoshkin** [comment]
При этом имейте ввиду, что мало того, что идиоты. Мы еще хитрые и упертые. Дешевле сразу сделать, как мы просим.
