### ISSUE TITLE
платежка печатается некорректно вместо Тренд Ип Тимошкин

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#23]
причем формируется правильно. Видео в скайпе

**Comment by AnnaSalikova** [comment]
Данные плательщика в печатную форму подставляются из соответствующего поля в документе. Изначально создали ПП для организации ИП Тимошкин, потом изменили организацию, перезаполнили документ. Данные для подстановки в печатную форму не перезаполнились - это ошибка, исправим. 
Сейчас исправьте данные по гиперссылке, и в печатную форму они выведутся правильно

**Comment by OTimoshkin** [comment]
вообщем нужно, чтобы данные перезаполнялись по кнопке "перезаполнить" и по кнопке "создать платежку"
Мне важно, чтобы было равенство: кнопка "презаполнить .. платежку, доверенность, заявку, приход" = "кнопка создать... платежку/доверенность/заявку/приход" Имею ввиду кнопки вверху формы и кнопки во вкладке "документы"

**Comment by AnnaSalikova** [comment]
Доработан механизм подстановки данных для печати в платежное поручение. При смене организации перезаполняются
