### ISSUE TITLE
не закрывается заказ, в случае, если оплатил клиент (по скайпу писал)

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#25]
![image](https://user-images.githubusercontent.com/27953665/80017039-9bd01b80-84dc-11ea-8afe-3ffcdcc9b331.png)
![image](https://user-images.githubusercontent.com/27953665/80017085-b0acaf00-84dc-11ea-9747-e61554b02597.png)

**Comment by AnnaSalikova** [comment]
ошибка исправлена.
