### ISSUE TITLE
пропадает поставщик и цены в форме заказа при создании нового договора

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#28]
![image](https://user-images.githubusercontent.com/27953665/80595986-4c36a600-8a2e-11ea-980f-c90828547d75.png)
очередность действий, описанная оператором:
1) создается заказ, выбирается поставщик, номенклатура, кол-во, цена поставщика
2) переходим в форму управление доставкой, создаем договор с поставщиком, вводим все данные для доверенности
3) выходим из формы управление доставкой и наблюдаем следующее:
- исчез поставщик
- исчезли входные цены
возможно ли сделать, чтобы при создании договора не исчезали ранее введенные данные?

**Comment by AnnaSalikova** [comment]
Спасибо за способ воспроизведения. Сейчас часть исправлений этой проблемы уже на аудите. 
Сейчас чтобы цены не исчезали, вам нужно после того, как создали и выбрали новый договор поставщика в форме Управление доставкой нажать кнопку Записать. потом переходить к остальным действиям. Сейчас часть исправлений этой проблемы уже на аудите

**Comment by AnnaSalikova** [comment]
Проверено в рабочей базе. Ошибка не воспроизводится по описанному алгоритму
