### ISSUE TITLE
путаница телефонов и емейлов в регистрах грузоотправителей, поставщиков и покупателей

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#29]
![image](https://user-images.githubusercontent.com/27953665/81277952-be763e80-905d-11ea-9614-8509af8a630b.png)

**Comment by OTimoshkin** [comment]
![image](https://user-images.githubusercontent.com/27953665/81279000-2c6f3580-905f-11ea-8bac-dfb9e2d1859f.png)

**Comment by OTimoshkin** [comment]
![image](https://user-images.githubusercontent.com/27953665/81279150-693b2c80-905f-11ea-8eea-9cc01e59396a.png)

**Comment by OTimoshkin** [comment]
![image](https://user-images.githubusercontent.com/27953665/81279351-b0c1b880-905f-11ea-8c19-335d51723038.png)

**Comment by OTimoshkin** [comment]
если ориентироваться на эти карточки клиентов, то получается, что в Снабстрой добавились телефоны наших поставщиков и телефоны грузоотправителей, в случае, когда мы что-либо покупали у снабстроя

**Comment by AnnaSalikova** [comment]
Добрый день. https://github.com/OTimoshkin/1CfreshKirpichTrade/issues/29#issuecomment-625143364 по этому вопросу ошибки нет: 
В заказе покупателя НФНФ- 000060 от 10.04 и  указан поставщик Снабстрой и стоит флаг "грузоотправитель тот же", при этом указан телефон на погрузке +79023108088. Этот номер был записан как телефон на погрузке в контакты контрагенту Снабстрой.

**Comment by AnnaSalikova** [comment]
https://github.com/OTimoshkin/1CfreshKirpichTrade/issues/29#issue-613907027 - проверила базу, ошибки так же нет. В системе есть заказ покупателя № НФНФ -000015  НФНФ-000016 от 30.03.2020: поставщик СНАБСТРОЙ ООО, стоит флаг грузоотправитель тот же и указан номер +78452393940. Номер по -правилам записан контрагенту СНАБСТРОЙ ООО как номер на погрузке.

**Comment by AnnaSalikova** [comment]
Адрес отгрузки: подставляется физический адрес грузоотправителя, если стоит флаг грузоотправитель тот же, то подставляется физический адрес поставщика. 
Телефон на погрузке - последний использованный телефон грузоотправителя (если стоит флаг, то телефон на погрузке поставщика)
Почта поставщика - всегда последняя использованная почта поставщика. 
Если вы вручную указываете новый телефон, он записывается как телефон на погрузке поставщику (если стоит флаг). Если после этого снять флаг и выбрать грузоотправителя, то этот номер запишется так же грузоотправителю. Записанный ранее номер у поставщика не удаляется (нет такого механизма).
Таким образом ошибки со стороны 1с нет. система работает в соответствии с ТЗ. Все неправильные номера телефонов созданы и добавлены в базу пользователями.
