### ISSUE TITLE
Исключение лишнего действия "выбор типа договора"

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#3]
![image_2020_04_02T07_52_39_442Z](https://user-images.githubusercontent.com/27953665/78228865-e5c67280-74d7-11ea-9f2c-49dfddd939eb.png)
![Uploading image_2020_04_02T07_51_23_859Z.png…]()

**Comment by AnnaSalikova** [comment]
Задача зафиксирована. Доработка функционала возможна

**Comment by OTimoshkin** [comment]
Тоже самое. Подарок.

**Comment by AnnaSalikova** [comment]
Сделана доработка. При создании договора из формы Управление доставкой (кнопка создать в поле Договор поставщика) создается договор с видом "С поставщиком"
