### ISSUE TITLE
ПРОПАДАЮТ ДАННЫЕ ПОСТАВЩИКОВ ЦЕН И ВОДИТЕЛЕЙ!!!!!!!!!!!!!! МОЖЕТ БЫТЬ ТАКОЕ????

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#32]
![image](https://user-images.githubusercontent.com/27953665/81917926-7ebfd180-95de-11ea-9b28-08aef374244d.png)

ПРОШУ РАССКАЗАТЬ ИСТОРИЮ ИЗМЕНЕНИЙ ЗАКАЗА.
МЫ 100% ОТПРАВЛЯЛИ ДОВЕРЕННОСТЬ НА ГУСЬКОВА ИГОРЯ 05.05.2020, затем сегодня зашли, там был водитель некто Бурлаков. Поставщик был СЗЛК, туда и отправляли доверенность.
Сейчас поставщик СНАБСТРОЙ, нет входных цен, водитель БУРЛАКОВ (оператор зачем-то опять исправила на ГУСЬКОВА)

**Comment by AnnaSalikova** [comment]
з постановки задачи следует:
05.05.2020 создан заказ покупателя №160, с контрагентом СЗЛК и водителем Гуськов Игорь. тогда же был создан и отправлен документ Доверенность поставщику СЗЛК с водителем Гуськов
14.05.2020 в форме Управления доставкой обнаружился водитель Бурлаков, поставщик СЗЛК.
14.05.2020 поставщик изменен на Снабстрой, водитель изменен на Гуськова.

Проверила данные в системе для восстановления истории изменений заказа покупателя № 160:
1. 05.05.2020 в 1с не зарегистрировано ни одной доверенности (нет созданных документов).
2. 05.05.2020 в системе не зарегистрировано ни одного события отправки электронных писем.
3. Доверенности на Гуськова Игоря с поставщиком СЗЛК в мае:
№ 107 - 06.05 - к Заказу покупателя 172 от 06.05.2020
№ 109 - 06.05 - к Заказу покупателя 174 от 06.05.2020
№ 115, от 07.05 к Заказу покупателя 181 от 07.05.2020
№ 118 от 07.05. к Заказу покупателя 188 от 07.05.2020
№ 126 от 08.05 к Заказу покупателя 193 от 08.05.2020 и так далее.
Более ранняя доверенность зарегистрирована 23.04 и ранее
4. Для водителя Бурлаков (А.Н) в системе зарегистрирована единственная доверенность № 121 от 08.05.2020 к Заказу покупателя 169 от 06.05.2020 (поставщик ЗАО "ЗАВОД ГСИ")
5. Для Заказа покупателя № 160 от 05.05.2020 ни в один из дней не зарегистрировано событий отправки писем или документов доверенности
6. Заказов поставщику с номенклатурой ""Кирпич 1,5 лицевой красный ( 250 *120*88) СЗЛК"в системе нет. Без заказа поставщику доверенность не может быть создана.
7. Для номенклатуры "Кирпич 1,5 лицевой красный ( 250 *120*88) СЗЛК" установлены цены для контрагентов в апреле 2020:

СЗЛК ООО вид цены поставщика (прайс) "цены поставки"
БИОТЕХ АО цены поставщика "оптовые цены"
ПРОМСНАБ ООО ГК, цена поставщика "оптовые цены".
Для контрагента СНАБСТРОЙ цены на эту номенклатуру никогда не устанавливались, поэтому в заказе покупателя Цены поставщика не заполнены.
8. Для заказа покупателя № 160 зарегистрирована только реализация товаров и услуг 14.05.2020.
9. История изменения формы Управления доставкой не ведется (так как регистр, для не предусмотрено типовым функционалом ведения истории и разработка функционала не была заложена в ТЗ). Доработать механизм регистрации истории изменения записей Управления доставкой технически возможно, требует отдельной оценки и проработки.
Вывод: для данного заказа покупателя с поставщиком Снабстрой или СЗЛК не зафиксировано факта создания или отправки доверенности или каких-либо документов, кроме Реализации. Возможные варианты развития событий:
1. Документы были созданы, помечены на удаление и удалены вместе с событиями (в этом случае все записи их журналов регистрации удаляются)
2. документы не были созданы для этого заказа, а были созданы для другого заказа покупателя
3. 05.05.2020 был сбой на сервере фреша и данные не были записаны в системе
Если требуется дальнейшее расследование, нужна архивная копия базы в промежутке от 06.05.2020 по 13.05.2020 для сравнения с текущей базой

**Comment by AnnaSalikova** [comment]
Ошибка с пропаданем данных не воспроизводится
