### ISSUE TITLE
Не вставляется е-мейл перевозчика при отправке заявки

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#4]
![image](https://user-images.githubusercontent.com/27953665/78237880-963a7380-74e4-11ea-9c8f-5a8d593b0b10.png)

**Comment by AnnaSalikova** [comment]
Взято в работу

**Comment by AnnaSalikova** [comment]
Добрый день. Проверено под пользователем Маргарита: почта перевозчика подставляется, если заполнена в форме Управления доставкой. Возможно, на момент формирования письма не был заполнен адрес электронной почты у перевозчика? 
Если проблема сохраняется и при заполненном адресе перевозчика в форме Управления доставкой в письмо он не подставляется, то предлагаю созвониться в скайп либо организовать подключение по тимвьювер на рабочее место сотрудника, чтобы посмотреть детально в чем проблема
