### ISSUE TITLE
в смс не ставится дата выгрузки

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#6]
![image](https://user-images.githubusercontent.com/27953665/78239006-e1a15180-74e5-11ea-92ae-b52f1e9abeb9.png)

**Comment by AnnaSalikova** [comment]
дата выгрузки в смс не заполняется, если не заполнен соответствующий реквизит в форме Управление доставкой.
Выполнена проверка  под пользователем Дартаева. При заполненном поле Дата выгрузки в форме она подставляется в смс

**Comment by OTimoshkin** [comment]
тоже зачем-то удалили баг. Не дали крови попить.
