### ISSUE TITLE
при отправке смс не подтягиваются контакты

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#7]
если забиваю имя контакта, нужно, чтобы хотя бы первый номер контакта подтягивался автоматически, этого не происходит

**Comment by AnnaSalikova** [comment]
Уточните пожалуйста в чем проблема и в чем суть задачи. Для решения ошибки - номер заказа куда не подтягиваются контакты, под каким пользователем, чьи контакты

**Comment by OTimoshkin** [comment]
Вы ее уже решили тихонько. Боитесь, наверное.
