### ISSUE TITLE
без НДС в табличной части, если стоит ИП Тимошкин

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#8]
![image](https://user-images.githubusercontent.com/27953665/78289179-6a41e100-752a-11ea-9832-46268f6c8fd3.png)

**Comment by AnnaSalikova** [comment]
в Заказа покупателя ставка НДС подставляется из карточки номенклатуры в зависимости от настройки Налоги в раздле Цены и валюты Заказа покупателя: 
- Если организация на общей системе налогообложения, то в Заказе покупателя в настройку ЦЕны и валюты начение "Налоги" ставится "Облагается (с НДС", и дальше ставка НДС для номенклатуры подставляется из карточки.
- Если организация на упрощенной системе или только на ЕНВД, то в заказ покупателя значение Налоги ставится "Не облагается (без НДС)", соответствнно, в документе не выделяется ндс.
Варианты настройки сисетмы (без доработок): 
Вариант 1. в Заказе покупателя нажать на гиперссылку под полем Организация и в открывшемся окне выбрать значение Налоги "Не облагается (без НДС)" - нажать ОК. В результате из документа уйдет ставка НДС, цены и сумма документа не изменятся 
![image](https://user-images.githubusercontent.com/63094191/78361258-4d68e480-75e2-11ea-844a-8d72f5f106c4.png)

Вариант 2. Изменить настройки налогообложение организации (см. Рис.2)
Перейти в справочник Организации - выбрать организацию ИП Тимошкин, развернуть группу настроек Налогообложение, Выбрать систему налогообложения Упрощенную или Только ЕНВД (в зависимости от того, какая система является базовой. Если программа не используется для сдачи отчетности, то тожно выбрать Только ЕНВД). ЗАписать изменения. 
После этого в документы продажи всегда будет подставляться значение налогообложения "Не облагается (без НДС)" и ставка НДС в документах не будет подбираться.  
 
![image](https://user-images.githubusercontent.com/63094191/78361317-696c8600-75e2-11ea-8574-b5e1b2490dea.png)


Устраивают ли вас предложенные варианты настройки типового функционала или нужна доработка?

**Comment by AnnaSalikova** [comment]
в Заказа покупателя ставка НДС подставляется из карточки номенклатуры в зависимости от настройки Налоги в раздле Цены и валюты Заказа покупателя: 
- Если организация на общей системе налогообложения, то в Заказе покупателя в настройку ЦЕны и валюты начение "Налоги" ставится "Облагается (с НДС", и дальше ставка НДС для номенклатуры подставляется из карточки.
- Если организация на упрощенной системе или только на ЕНВД, то в заказ покупателя значение Налоги ставится "Не облагается (без НДС)", соответствнно, в документе не выделяется ндс.

Варианты настройки сисетмы (без доработок): 
Вариант 1. в Заказе покупателя нажать на гиперссылку под полем Организация и в открывшемся окне выбрать значение Налоги "Не облагается (без НДС)" - нажать ОК. В результате из документа уйдет ставка НДС, цены и сумма документа не изменятся 
![image](https://user-images.githubusercontent.com/63094191/78361517-be100100-75e2-11ea-94d1-511d97bc15de.png)

Вариант 2. Изменить настройки налогообложение организации 
Перейти в справочник Организации - выбрать организацию ИП Тимошкин, развернуть группу настроек Налогообложение, Выбрать систему налогообложения Упрощенную или Только ЕНВД (в зависимости от того, какая система является базовой. Если программа не используется для сдачи отчетности, то тожно выбрать Только ЕНВД). ЗАписать изменения. 
После этого в документы продажи всегда будет подставляться значение налогообложения "Не облагается (без НДС)" и ставка НДС в документах не будет подбираться.  
 
![image](https://user-images.githubusercontent.com/63094191/78361499-b05a7b80-75e2-11ea-90aa-65fcba82b245.png)

Устраивают ли вас предложенные варианты настройки типового функционала или нужна доработка?

**Comment by AnnaSalikova** [comment]
Отправила разъясения на почту. Здесь текст коверкается

**Comment by OTimoshkin** [comment]
вообщем я сделал, все как вы сказали, Аня. У меня ничего не получается. 
Я исправил режим налогообложения и написал, ИП Тимошкин "без НДС", далее ничего не изменилось. Все равно номенклатура вылезает с этим гребанным НДСом!!!!!
И каждый раз приходится тыкаться в эти гиперссылки, это не дело. 
Нужно чтобы в табличной части вылезало НДС или не НДС в зависимости от того, что прописано в карточке компании автоматически.

Даже, если это будет предмет доработки.

**Comment by AnnaSalikova** [comment]
Добрый день, Олег. Вы поменяли ставку НДС в настройках организации, а не изменили систему налогообложения. У вас по-прежнему "Общая", поэтому подставляется ставка НДС из карточки номенклатуры. 
Доработка, чтобы в Заказ покупателя подставлялась ставка НДС из Карточки организации - 3 часа.
