### ISSUE TITLE
Вставка номера договора автоматически

### ISSUE THREAD

**Issue by OTimoshkin** [OTimoshkin/1CfreshKirpichTrade#9]
![image](https://user-images.githubusercontent.com/27953665/78289649-2b605b00-752b-11ea-80a2-0a87fce2f53b.png)

**Comment by AnnaSalikova** [comment]
Поясните пожалуйста в чем проблема и в чем требуется доработка? Сейчас функционал работает именно так, как вы пишите: если с поставщиком один договор, то он и подставляется. Еще раз обращаю внимание, что договор должен быть именно " с поставщиком" а не "с покупателем" - это нужно для дальнейшей корректной работы функционала. Если у вас договор с покупателем, то нужно  либо создать отдельный договор с поставщиком, либо изменить на "С поставщиком".

**Comment by OTimoshkin** [comment]
Приходится делать два действия:
1) выбрать организацию
2) выбрать договор, даже если он один, так как, если не выберешь, поле будет пустым

Поэтому, в целях исключения второго действия прошу:
если мы выбрали организацию и у нее с поставщиком уже есть договор, пусть автоматически встанет и не надо будет туда тыкаться.

**Comment by OTimoshkin** [comment]
при условии, что этот договор 1, если договора 2 - тогда, пусть поле остается пустым - "нужно потыкаться"

**Comment by AnnaSalikova** [comment]
Олег, добрый день, вы пишете: "Поэтому, в целях исключения второго действия прошу:
если мы выбрали организацию и у нее с поставщиком уже есть договор, пусть автоматически встанет и не надо будет туда тыкаться".
Еще раз,  повторю: программа так и работает.
Если у вас договор не подставляется, значит 
1) это договор с ПОКУПАТЕЛЕМ. программа его не подставит. Замените в договорах вид на "С ПОСТАВЩИКОМ" и программа будет их подставлять 
2) у контрагента с организацией нет договора -создайте договор с видом "С ПОСТАВЩИКОМ"
3) у контрагента несколько договоров - тогда один договоров с видом "С ПОСТАВЩИКОМ" отметьте как "Основной" (зеленая галочка у договора).
Я настаиваю на необходимости правильно указывать вид договора, так как это влияет на его использование в дальнейших документах. так как это просто, соответствует правильной методике учета и не повлечет дополнительных затрат с вашей стороны.
Если вы хотите, чтобы вместо договора с видом "С ПОСТАВЩИКОМ" подставлялся договор с видом "С ПОКУПАТЕЛЕМ", то придется дорабатывать типовой функционал формирования Заказа поставщику, Приходной накладной от поставщика и платежного поручения.  Согласны на доработку? Тогда пришлю вам оценку на согласование

**Comment by OTimoshkin** [comment]
Анна, добрый день. Задублировал данный кейс. Программа так себя не ведет, как вы пишите:
"Еще раз, повторю: программа так и работает.
--------- на "С ПОСТАВЩИКОМ" и программа будет их подставлять"
В опровержении внутри кейса увидите скриншоты.
Ссылку сейчас сюда пришлю, либо этот кейс попробую сюда запихнуть, потому что они схожи.

**Comment by OTimoshkin** [comment]
https://github.com/OTimoshkin/1CfreshKirpichTrade/issues/16

**Comment by OTimoshkin** [comment]
это ссылка по вышеописанному случаю

**Comment by AnnaSalikova** [comment]
Добрый день. 
1. За отображение списка договоров отвечает механизм платформы: в выпадающий список выводятся последние выбранные значения. Если ничего не выбирали из списка, то нечему отображаться. Это типовой механизм и мы его не передедывали. Уточню у разработчика сколько потребуется на его переделку.
2. Подстановка договора. Действительно, если сначала выбрать поставщика, потом организацию, договор не подставляется. Поправим этот механизм. Во всех тестах использовался рекомендованный в методиках учета процесс выбора 1)сначала  Организация затем 2) Поставщик. Рекомендую вам использовать эту последовательность действий до внесения исправлений.

Прошу в будущем подробно описывать последовательность действий (Последовательность нажатия кнопок и изменения данных в полях) - это существенно сократит время на выяснения каким образом воспроизводится ошибка.

**Comment by AnnaSalikova** [comment]
Сделана доработка: исправлен порядок выбора поставщика и организации для подстановки договора
